### ISSUE TITLE
Barely loads; slow FPS on iPhone6?

### ISSUE THREAD

**Issue by joshbax** [FlexMonkey/ParticleCam#2]
I could only get it to load once, and even then it only ran at maybe 1 frame a second. Is there a setting somewhere that I'm missing? 

All other metal samples work great though. 

iPhone6, iOS 9.3.2

**Comment by FlexMonkey** [comment]
Hi,

Unfortunately, I don't have a 6 to try, but on my 6s, I get 30fps. The default particle count is one million - have you tried reducing that (line 28 in `ParticleLab.swift`.

Simon

**Comment by joshbax** [comment]
Yeah, confirmed it works great on a 6s. 
Reducing the AVCaptureSession output quality and lowering the particle count yields only marginal performance improvements on iPhone6. Apparently the older device is just too slow this. I purchased your book, thanks for the getting back.

**Comment by FlexMonkey** [comment]
I actually originally wrote it targeting a 6 - without using the CoreImage wrapper. If you can checkout the project in its state last August, it should work better (may need some tweaking to update to latest Swift syntax). 

Thanks for purchasing the book!
